name: Deploy to S3 + CloudFront

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  S3_BUCKET: ararise-web-prod
  CLOUDFRONT_DIST_ID: EWY2C4MJVXFBV
  BUILD_DIR: dist

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::820827290358:role/github-actions-ararise-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload build to S3
        run: aws s3 sync ./${{ env.BUILD_DIR }} s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation \
          --distribution-id ${{ env.CLOUDFRONT_DIST_ID }} \
          --paths "/*"
